//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedications
    {
        public int ID_PatientMedication { get; set; }
        public int ID_Patient { get; set; }
        public int ID_Medication { get; set; }
    
        public virtual Medications Medications { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
